#!/bin/bash
# file: /usr/local/bin/kill_ports

RED='\033[0;31m'
NC='\033[0m' # No Color

# Function to kill a single port
kill_port() {
    echo -e "Killing ${RED}port $1${NC}..."
    lsof -ti tcp:$1 | xargs kill 2>/dev/null
}

# Kill default ports 3001-3006 and 8080
default_ports="7030 7031 7032 7033 7034 7035 7036 7037 7038 7039 7040"

# Combine default ports with any additional ports provided as arguments
all_ports="$default_ports $@"

# Kill all specified ports
for port in $all_ports; do
    kill_port $port
done

echo "Done killing ports!"