[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = true

[profile.ci]
fuzz = { runs = 10_000 }
invariant = { runs = 1_000 }

# Network configurations - Flow EVM Testnet only
[rpc_endpoints]
flow_testnet = "https://testnet.evm.nodes.onflow.org"

# Gas configuration for Flow EVM Testnet
# Using 2 gwei (2000000000 wei) to ensure transactions are processed
[profile.flow_testnet]
gas_price = 2000000000  # 2 gwei in wei

# Deployment optimization to prevent hanging on Flow EVM Testnet
[profile.fast_deploy]
gas_price = 2000000000
# These settings speed up deployments by reducing confirmation wait times

# Etherscan configuration (commented out for initial deployment)
# [etherscan]
# flow_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://evm-testnet.flowscan.io" }
# ethereum_mainnet = { key = "${ETHERSCAN_API_KEY}" }
# ethereum_sepolia = { key = "${ETHERSCAN_API_KEY}" }
# polygon_mainnet = { key = "${POLYGONSCAN_API_KEY}", url = "https://api.polygonscan.com/api" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config 